"""initial schema

Revision ID: ea498609cf8d
Revises: 
Create Date: 2026-09-30 14:19:20.698673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea498609cf8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('instagram_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instagram_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('follows_count', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_accounts_instagram_user_id'), 'instagram_accounts', ['instagram_user_id'], unique=True)
    op.create_index(op.f('ix_instagram_accounts_user_id'), 'instagram_accounts', ['user_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_state_hash'), 'oauth_states', ['state_hash'], unique=True)
    op.create_table('instagram_daily_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reach', sa.Float(), nullable=True),
    sa.Column('views', sa.Float(), nullable=True),
    sa.Column('likes', sa.Float(), nullable=True),
    sa.Column('comments', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('saves', sa.Float(), nullable=True),
    sa.Column('replies', sa.Float(), nullable=True),
    sa.Column('reposts', sa.Float(), nullable=True),
    sa.Column('total_interactions', sa.Float(), nullable=True),
    sa.Column('accounts_engaged', sa.Float(), nullable=True),
    sa.Column('follows_and_unfollows', sa.Float(), nullable=True),
    sa.Column('profile_links_taps', sa.Float(), nullable=True),
    sa.Column('follower_count_delta', sa.Float(), nullable=True),
    sa.Column('followers_snapshot', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_account_id', 'metric_date', name='uq_daily_account_date')
    )
    op.create_index('ix_daily_account_date', 'instagram_daily_insights', ['instagram_account_id', 'metric_date'], unique=False)
    op.create_index(op.f('ix_instagram_daily_insights_instagram_account_id'), 'instagram_daily_insights', ['instagram_account_id'], unique=False)
    op.create_table('instagram_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('instagram_media_id', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=True),
    sa.Column('media_product_type', sa.String(length=16), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_account_id', 'instagram_media_id', name='uq_media_account_media')
    )
    op.create_index(op.f('ix_instagram_media_instagram_account_id'), 'instagram_media', ['instagram_account_id'], unique=False)
    op.create_index(op.f('ix_instagram_media_posted_at'), 'instagram_media', ['posted_at'], unique=False)
    op.create_index('ix_media_account_posted', 'instagram_media', ['instagram_account_id', 'posted_at'], unique=False)
    op.create_table('instagram_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=True),
    sa.Column('sync_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_sync_logs_instagram_account_id'), 'instagram_sync_logs', ['instagram_account_id'], unique=False)
    op.create_table('instagram_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_account_id')
    )
    op.create_table('instagram_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('metric_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['instagram_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'metric_name', 'period', name='uq_insight_media_metric_period')
    )
    op.create_index(op.f('ix_instagram_insights_instagram_account_id'), 'instagram_insights', ['instagram_account_id'], unique=False)
    op.create_index(op.f('ix_instagram_insights_media_id'), 'instagram_insights', ['media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_insights_media_id'), table_name='instagram_insights')
    op.drop_index(op.f('ix_instagram_insights_instagram_account_id'), table_name='instagram_insights')
    op.drop_table('instagram_insights')
    op.drop_table('instagram_tokens')
    op.drop_index(op.f('ix_instagram_sync_logs_instagram_account_id'), table_name='instagram_sync_logs')
    op.drop_table('instagram_sync_logs')
    op.drop_index('ix_media_account_posted', table_name='instagram_media')
    op.drop_index(op.f('ix_instagram_media_posted_at'), table_name='instagram_media')
    op.drop_index(op.f('ix_instagram_media_instagram_account_id'), table_name='instagram_media')
    op.drop_table('instagram_media')
    op.drop_index(op.f('ix_instagram_daily_insights_instagram_account_id'), table_name='instagram_daily_insights')
    op.drop_index('ix_daily_account_date', table_name='instagram_daily_insights')
    op.drop_table('instagram_daily_insights')
    op.drop_index(op.f('ix_oauth_states_state_hash'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_instagram_accounts_user_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_instagram_user_id'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
